from collections import OrderedDict

ui_to_gamestates_map = OrderedDict(
    {
        "pre_game": {
            "any": [
                ["play", "left_menu_dark"],
                ["play", "challenge_btn_orange"],
                ["game_about_to_start_box_white", "left_menu_dark"],
                ["battle_royale_start_menu_w_logo"],
                ["game_about_to_start_box_white", "next_orange_btn"],
                ["setup_round_time_limit_box"],
                ["battle_royale_start_menu_w_logo"],
                ["start_game"],
                ["invite_friends"],
                ["next_orange_btn"],
                ["start_challenge_orange"],
                ["start_game"],
            ],
            "exact": [],
            "ignore": [["video"]],
        },
        "between_rounds": {
            "any": [
                ["left_menu_dark", "challenge_high_score_board"],
                ["play_next_round", "points_bar", "did_you_enjoy_this_location"],
                ["play_next_round", "points_bar_two_bars", "did_you_enjoy_this_location"],
                ["btw_rounds_points_bar_blue_wide", "play_next_round"],
                ["battle_royale_btw_rounds_green_box", "br_players_box_white"],
                ["battle_royale_btw_rounds_red_box", "br_players_box_white"],
                ["battle_royale_game_over_dark_box", "br_players_box_white"],
                ["battle_royale_knocked_out_end_game_red", "br_players_box_white"],
            ],
            "exact": [
                ["in_game_mini_map", "status_bar", "points_bar", "game_title"],
                ["btw_rounds_points_bar_blue_wide"],
            ],
            "ignore": [["video"]],
        },
        "between_round_or_game_ambiguous": {
            "any": [
                ["points_bar_two_bars", "did_you_enjoy_this_location", "status_bar"],
                ["between_rounds_box_white", "did_you_enjoy_this_location", "status_bar"],
                ["points_bar_two_bars", "status_bar"],
                ["points_bar_two_bars", "status_bar", "game_title"],
                ["points_bar_two_bars", "did_you_enjoy_this_location", "status_bar", "game_title"],
                ["points_bar_two_bars", "status_bar", "share_challenge_box_white"],
                ["points_bar_two_bars", "challenge_high_score_board", "status_bar"],
                ["points_bar_two_bars", "status_bar", "game_title", "share_challenge_box_white"],
                [
                    "between_rounds_box_white",
                    "did_you_enjoy_this_location",
                    "status_bar",
                    "game_title",
                ],
                ["points_bar", "left_menu_dark"],
                ["points_bar", "did_you_enjoy_this_location"],
                ["points_bar_two_bars", "did_you_enjoy_this_location"],
                ["status_bar", "points_bar", "game_title"],
                ["left_menu_dark"],
                ["left_menu_dark", "status_bar", "game_title"],
                ["left_menu_dark", "other"],
                ["left_menu_dark", "points_bar"],
                ["left_menu_dark", "points_bar_two_bars"],
            ],
            "exact": [],
            "ignore": [["video"]],
            "do_not_match": [
                [
                    "in_game_mini_map",
                    "in_game_map_expanded",
                    "guess",
                    "guess_grey",
                    "make_a_guess",
                    "place_your_pin_grey",
                    "guess_w_icon_only",
                    "guess_expanded",
                    "guess_grey_expanded",
                    "make_a_guess_expanded",
                    "place_your_pin_grey_expanded",
                    "guess_w_icon_only_expanded",
                ],
            ],
        },
        "in_game": {
            "any": [
                # The ones with "in_game_mini_map" in first position will get auto-expanded:
                ["in_game_mini_map", "guess"],
                ["in_game_mini_map", "guess_grey"],
                ["in_game_mini_map", "make_a_guess"],
                ["in_game_mini_map", "place_your_pin_grey"],
                ["in_game_mini_map", "guess_w_icon_only"],
                # Won't get expanded:
                # ["status_bar", "in_game_mini_map"],
                # ["status_bar", "in_game_map_expanded"],
                ["status_bar_purple", "in_game_mini_map"],
                ["status_bar_purple", "in_game_map_expanded"],
                ["game_title", "in_game_map_expanded", "status_bar", "status_bar_white"],
                ["game_title", "in_game_mini_map", "status_bar"],
                ["game_title", "in_game_map_expanded", "status_bar"],
                ["game_title", "guess", "status_bar", "status_bar_white"],
                ["game_title", "guess_grey", "status_bar", "status_bar_white"],
                ["game_title", "make_a_guess", "status_bar", "status_bar_white"],
                ["game_title", "place_your_pin_grey", "status_bar", "status_bar_white"],
                ["game_title", "guess_w_icon_only", "status_bar", "status_bar_white"],
                ["game_title", "guess_expanded", "status_bar", "status_bar_white"],
                ["game_title", "guess_grey_expanded", "status_bar", "status_bar_white"],
                ["game_title", "make_a_guess_expanded", "status_bar", "status_bar_white"],
                ["game_title", "place_your_pin_grey_expanded", "status_bar", "status_bar_white"],
                ["game_title", "guess_w_icon_only_expanded", "status_bar", "status_bar_white"],
                ["game_title", "guess_grey", "in_game_mini_map", "status_bar", "status_bar_white"],
                ["make_a_guess", "status_bar", "game_title"],
                ["guess_grey", "status_bar", "game_title"],
                ["guess", "status_bar", "game_title"],
                ["in_game_mini_map", "status_bar", "status_bar_white"],
                ["in_game_map_expanded", "status_bar", "status_bar_white"],
                # game_title, in_game_mini_map, make_a_guess, status_bar
            ],
            "exact": [
                ["status_bar_white", "status_bar", "game_title"],
                # ["game_title", "status_bar", "status_bar_white", "url"]
                ["status_bar_white", "other", "status_bar", "game_title"],
                ["game_title", "status_bar_white", "make_a_guess_expanded", "status_bar"],
                ["status_bar_purple"],
                ["game_title", "in_game_mini_map", "status_bar", "status_bar_white"],
                ["game_title", "in_game_map_expanded", "status_bar", "status_bar_white"],
            ],
            # Ignore these during matching elements in the 'any' and 'exact' lists:
            "ignore": [
                [
                    "between_rounds_box_white",
                    "btw_rounds_points_bar_blue_wide",
                    "challenge_high_score_board",
                    "did_you_enjoy_this_location",
                    "high_score_box",
                    "leader_board",
                    "left_menu_dark",
                    "play_next_round",
                    "play",
                    "points_bar_two_bars",
                    "points_bar",
                    "show_full_results",
                    "show_high_score",
                    "try_another_map",
                    "battle_royale_start_menu_w_logo",
                    "url",
                    "video",
                    "battle_royale_btw_rounds_green_box",
                    "battle_royale_btw_rounds_red_box",
                    "battle_royale_game_over_dark_box",
                    "battle_royale_knocked_out_end_game_red",
                ]
            ],
            "do_not_match": [
                ["google_mini_map", "other"],
            ],
        },
        "between_games": {
            "any": [
                ["left_menu_dark", "challenge_high_score_board"],
                ["points_bar", "show_high_score"],
                ["points_bar_two_bars", "show_high_score"],
                ["try_another_map", "points_bar_two_bars", "show_full_results"],
                ["points_bar_two_bars", "show_full_results"],
                ["high_score_box", "leader_board"],
                ["battle_royale_game_over_dark_box"],
                ["battle_royale_knocked_out_end_game_red"],
                ["btw_rounds_points_bar_blue_wide", "game_breakdown_blue", "play_again"],
                ["btw_rounds_points_bar_blue_wide", "view_summ_green_on_blue"],
            ],
            "exact": [],
            "ignore": [["video"]],
        },
        "out_of_game": {
            "any": [
                ["google_mini_map"],
            ],
            "exact": [
                [],
                ["other"],
                ["video"],
            ],
        },
        "unknown": {
            "any": [],
            "exact": [],
        },
    }
)
